### PR TITLE
Zde je licencia

### PR DESCRIPTION
**Pull request by Milosezemanafanousek**
Pls akcept 🥺

### CODE REVIEW

**Comment by Milosezemanafanousek** [comment]
lgtm

**Comment by Milosezemanafanousek** [comment]
⛵ it

**Comment by Milosezemanafanousek** [comment]
> ⛵ it

ok, i will ⛵ it then

**Comment by Milosezemanafanousek** [comment]
> lgtm

cool, thanks grandpa

**Comment by Milosezemanafanousek** [comment]
it's merged now, thanks for your valuable feedback guys

**Comment by Milosezemanafanousek** [comment]
> it's merged now, thanks for your valuable feedback guys

thank you for your high quality effort good sir

**Comment by Milosezemanafanousek** [comment]
> it's merged now, thanks for your valuable feedback guys

yeah you ⛵d it really well

**Comment by Milosezemanafanousek** [comment]
wow thanks guys gn

**Comment by terp1s** [comment]
Xdd jaktoze si to mergnul sám? Mně nechodí upozornění na mail sry, jsem si toho všimla až teď

**Pull request merged**
